const puzzles = [
  'Es war einmal ein kleines süßes Mädchen, das hatte jedermann lieb, der sie nur ansah, am allerliebsten aber ihre Großmutter, die wusste gar nicht, was sie alles dem Kinde geben sollte. Einmal schenkte sie ihm ein Käppchen von rotem Samt, und weil ihm das so wohl stand, und es nichts anders mehr tragen wollte, hieß es nur das Rotkäppchen.',
  'FTXBS FJONB MFJOL MFJOF TTVFT TFTNB FEDIF OEBTI BUUFK FEFSN BOOMJ FCEFS TJFOV SBOTB IBNBM MFSMJ FCTUF OBCFS JISFH SPTTN VUUFS EJFXV TTUFH BSOJD IUXBT TJFBM MFTEF NLJOE FHFCF OTPMM UFFJO NBMTD IFOLU FTJFJ INFJO LBFQQ DIFOW POSPU FNTBN UVOEX FJMJI NEBTT PXPIM TUBOE VOEFT OJDIU TBOEF STNFI SUSBH FOXPM MUFIJ FTTFT OVSEB TSPUL BFQQD IFO',
  'ZTYNV ZJJUR JJZTY EZTYK JNVZJ J',
  'OZZSK CZZSB WBRSB VWAAS ZOPSF BWSAO BRKWZ ZGHSF PSB',
  'OTPOP FEDNS PYDTY OPTYR PXPTY RPQLP SCWTN SPDGZ WVDTP KTPSP YFYPC HLCEP EPTYR POTNS ELFDO PCELD NSPFY OMPRT YYPYP TYRPD ACLPN SFPMP CASTW ZDZAS TPSPT YCTNS SPTYP',
  'URJZJ KJTYF VESVZ UVEUV LKJTY VEBVZ EVIZJ KJFMV IILVT BKURJ JVIEZ TYKVZ EVEEF TYMVI ILVTB KVIVE WRVEU VUVIZ YEMVI JKVYK YVZEI ZTYYV ZEV',
  'CHDRD GDMCD MRHMC DRMHB GSCHD RHBGE TDQRD GDMCG ZKSDM HLLDQ MTQCH DAKHM CDM',
  'JKXKO TFOMK JKXKO TKTUF KRUZV KRFCO XQROI NHXGA INZOY ZJKXU FKRUZ HKXTN GXJMX FOSKQ',
  'PYLMO WBOHA YHMIF FNYGU HHUWB AYVYH QYLQY CMMIV MCYQC YXYLE IGGYH IMWUL QCFXY'
];

export default puzzles;
